import type { HubItem } from "./types";

export const SEED_ITEMS: HubItem[] = [
  {
    id: "church-homepage",
    name: "교회 홈페이지",
    description: "컨빌 교회 공식 홈페이지 (v2)",
    url: "https://convill-homepage-ver2.vercel.app/index.html",
    categories: ["교회"],
    type: "링크",
  },
  {
    id: "blog-landing-demo",
    name: "시공사 블로그 랜딩 데모 페이지",
    description: "인테리어 시공사용 블로그 랜딩 페이지 데모",
    url: "https://connectvillage-hub.github.io/convil-blog-landing/",
    categories: ["블로그"],
    type: "링크",
  },
  {
    id: "content-automation",
    name: "콘텐츠 자동 업로드",
    description: "콘텐츠 자동 업로드 안내 페이지",
    url: "https://connectvillage-hub.github.io/convil-content-automation/",
    categories: ["고객소통"],
    type: "링크",
  },
  {
    id: "instagram-cardnews-skill",
    name: "인스타그램 카드뉴스 매거진 생성 스킬",
    description: "인스타그램용 카드뉴스 자동 생성 스킬",
    categories: ["콘텐츠 제작"],
    type: "스킬",
  },
  {
    id: "church-homepage-admin",
    name: "교회 홈페이지 관리자",
    description: "교회 홈페이지 관리자 페이지",
    url: "https://convill-homepage-ver2.vercel.app/admin/",
    categories: ["교회"],
    type: "링크",
  },
  {
    id: "church-links-collection",
    name: "교회 브랜딩 / 고객소통 링크 모음",
    description: "교회 브랜딩 고객 응대용 링크 모음",
    url: "https://connectvillage-hub.github.io/church-links/",
    categories: ["고객소통", "교회"],
    type: "링크",
  },
  {
    id: "church-banner-guide",
    name: "교회 현수막 안내",
    description: "교회별 현수막 제작 안내 (URL ?church= 파라미터)",
    url: "https://connectvillage-hub.github.io/church-banner/?church=컨빌교회",
    categories: ["교회"],
    type: "링크",
  },
  {
    id: "church-logo-intake",
    name: "교회 로고 작업 접수",
    description: "교회 로고 제작 의뢰 접수 페이지 (준비 중)",
    categories: ["교회"],
    type: "링크",
  },
  {
    id: "church-logo-process",
    name: "교회 로고 제작 안내",
    description: "교회 로고 제작 프로세스 안내",
    url: "https://connectvillage-hub.github.io/convil-logo-process/",
    categories: ["고객소통", "교회"],
    type: "링크",
  },
  {
    id: "blog-automation",
    name: "블로그 자동화",
    description: "로컬 블로그 자동화 도구 (blog-automation-v3)",
    categories: ["블로그"],
    type: "로컬",
  },
  {
    id: "content-checklist",
    name: "양식 콘텐츠 제작 체크리스트",
    description: "정형 콘텐츠 제작 체크리스트 (로컬)",
    categories: ["콘텐츠 제작"],
    type: "로컬",
  },
  {
    id: "threads-content-skill",
    name: "스레드 콘텐츠 분석 및 추천 자동화",
    description: "Threads(스레드) 콘텐츠 분석 및 추천 자동화 스킬",
    categories: ["콘텐츠 제작"],
    type: "스킬",
  },
];
